POST http://127.0.0.1:5001/solve
Content-Type: application/json

{
  "projects": [
    {
      "name": "Project_1",
      "start": 0,
      "end": 10,
      "roles": {
        "drilling_engineer": 2,
        "geologist": 1,
        "mechanical_engineer": 1,
        "mud_engineer": 1
      }
    }
  ],
  "employees": [
    {
      "name": "Employee_1",
      "role": "drilling_engineer",
      "availability": [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
      "expertise": 100,
      "team": "A"
    }
  ],
  "weeks": 52,
  "shift_system": "3x3"
}



### Test solve with small team
POST http://127.0.0.1:5001/solve
Content-Type: application/json

{
  "Engineer": 5,
  "Specialist": 2,
  "Care Worker": 8,
  "Others": 3,
  "Admin": 1
}

### Start : week number 1-48

### Availability : 1-12


### Final Test
POST http://localhost:5001/solve
Content-Type: application/json

{
  "projects": [
    {
      "name": "Project Alpha",
      "start": 0,
      "end": 3,
      "roles": {
        "developer": 2
      }
    }
  ],
  "employees": [
    {
      "name": "Alice",
      "role": "developer",
      "expertise": 5,
      "availability": [1,1,1,1,1,1]
    },
    {
      "name": "Bob",
      "role": "developer",
      "expertise": 3,
      "availability": [1,1,1,1,1,1]
    },
    {
      "name": "Alice1",
      "role": "developer",
      "expertise": 5,
      "availability": [1,1,1,1,1,1]
    },
    {
      "name": "Bob1",
      "role": "developer",
      "expertise": 3,
      "availability": [1,1,1,1,1,1]
    },
    {
      "name": "Alice2",
      "role": "developer",
      "expertise": 5,
      "availability": [1,1,1,1,1,1]
    },
    {
      "name": "Bob2",
      "role": "developer",
      "expertise": 3,
      "availability": [1,1,1,1,1,1]
    },
    {
      "name": "Alice3",
      "role": "developer",
      "expertise": 5,
      "availability": [1,1,1,1,1,1]
    },
    {
      "name": "Bob3",
      "role": "developer",
      "expertise": 3,
      "availability": [1,1,1,1,1,1]
    },
    {
      "name": "Alice4",
      "role": "developer",
      "expertise": 5,
      "availability": [1,1,1,1,1,1]
    },
    {
      "name": "Bob4",
      "role": "developer",
      "expertise": 3,
      "availability": [1,1,1,1,1,1]
    },
    {
      "name": "Alice5",
      "role": "developer",
      "expertise": 5,
      "availability": [1,1,1,1,1,1]
    },
    {
      "name": "Bob5",
      "role": "developer",
      "expertise": 3,
      "availability": [1,1,1,1,1,1]
    },
    {
      "name": "Alice6",
      "role": "developer",
      "expertise": 5,
      "availability": [1,1,1,1,1,1]
    },
    {
      "name": "Bob6",
      "role": "developer",
      "expertise": 3,
      "availability": [1,1,1,1,1,1]
    },
    {
      "name": "Alice7",
      "role": "developer",
      "expertise": 5,
      "availability": [1,1,1,1,1,1]
    },
    {
      "name": "Bob7",
      "role": "developer",
      "expertise": 3,
      "availability": [1,1,1,1,1,1]
    },
    {
      "name": "Alice8",
      "role": "developer",
      "expertise": 5,
      "availability": [1,1,1,1,1,1]
    },
    {
      "name": "Bob8",
      "role": "developer",
      "expertise": 3,
      "availability": [1,1,1,1,1,1]
    }
  ],
  "weeks": 48,
  "shift_system": "4x4"
}


### Final Test 2
POST http://localhost:5001/solve
Content-Type: application/json

{
  "projects": [
    {
      "name": "Project A",
      "roles": {
        "Engineer": 3,
        "Manager": 1
      },
      "start": 0,
      "end": 4
    },
    {
      "name": "Project B",
      "roles": {
        "Technician": 2
      },
      "start": 2,
      "end": 6
    }
  ],
  "employees": [
    {
      "name": "John Doe",
      "role": "Engineer",
      "availability": [1, 1, 1, 1, 1, 0, 0],
      "expertise": 10
    },
    {
      "name": "Jane Smith",
      "role": "Manager",
      "availability": [1, 1, 0, 0, 1, 1, 0],
      "expertise": 8
    },
    {
      "name": "Mark Johnson",
      "role": "Technician",
      "availability": [1, 0, 1, 1, 0, 1, 1],
      "expertise": 6
    }
  ],
  "weeks": 7,
  "shift_system": "4x4"
}


### Final Test 3
POST http://localhost:5000/solve
Content-Type: application/json

{
  "projects": [
    {
      "name": "Project A",
      "roles": {
        "Automation Specialist": 0,
        "Drilling Engineer": 10,
        "Geologist": 2,
        "Mechanical Engineer": 5,
        "Mud Engineer": 4,
        "Operations Engineer": 9,
        "Rig Manager": 2,
        "Water Engineer": 1
      },
      "start": 0,
      "end": 15
    }
  ],
  "employees": [
    {
    "name": "John Doe",
    "role": "Automation Specialist",
    "availability": [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    "expertise": 10
  },
  {
    "name": "Jane Smith",
    "role": "Automation Specialist",
    "availability": [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    "expertise": 8
  },
  {
    "name": "Mark Johnson",
    "role": "Automation Specialist",
    "availability": [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    "expertise": 6
  },
  {
    "name": "Alice Brown",
    "role": "Automation Specialist",
    "availability": [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    "expertise": 9
  },
  {
    "name": "Bob Green",
    "role": "Drilling Engineer",
    "availability": [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    "expertise": 7
  },
  {
    "name": "Sara White",
    "role": "Drilling Engineer",
    "availability": [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    "expertise": 5
  },
  {
    "name": "Tom Black",
    "role": "Drilling Engineer",
    "availability": [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    "expertise": 4
  },
  {
    "name": "Emily Davis",
    "role": "Geologist",
    "availability": [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    "expertise": 6
  },
  {
    "name": "Carlos Martinez",
    "role": "Geologist",
    "availability": [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    "expertise": 7
  },
  {
    "name": "Sophie Wilson",
    "role": "Mechanical Engineer",
    "availability": [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    "expertise": 8
  },
  {
    "name": "David Harris",
    "role": "Mechanical Engineer",
    "availability": [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    "expertise": 6
  },
  {
    "name": "Olivia Taylor",
    "role": "Mechanical Engineer",
    "availability": [1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0],
    "expertise": 9
  },
  {
    "name": "Luke Scott",
    "role": "Mud Engineer",
    "availability": [0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0],
    "expertise": 6
  },
  {
    "name": "Laura Lee",
    "role": "Mud Engineer",
    "availability": [1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1],
    "expertise": 5
  },
  {
    "name": "Laura Lee 2",
    "role": "Operations Engineer",
    "availability": [1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1],
    "expertise": 5
  },
  {
    "name": "Laura Lee",
    "role": "Operations Engineer",
    "availability": [1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1],
    "expertise": 5
  },
  {
    "name": "Laura Lee",
    "role": "Operations Engineer",
    "availability": [1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1],
    "expertise": 5
  },
  {
    "name": "Laura Lee",
    "role": "Operations Engineer",
    "availability": [1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1],
    "expertise": 5
  },
  {
    "name": "Laura Lee",
    "role": "Rig Manager",
    "availability": [1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1],
    "expertise": 5
  },
  {
    "name": "Laura Lee",
    "role": "Rig Manager",
    "availability": [1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1],
    "expertise": 5
  },
  {
    "name": "Laura Lee",
    "role": "Rig Manager",
    "availability": [1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1],
    "expertise": 5
  },
  {
    "name": "Laura Lee",
    "role": "Water Engineer",
    "availability": [1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1],
    "expertise": 5
  },
  {
    "name": "Laura Lee",
    "role": "Water Engineer",
    "availability": [1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1],
    "expertise": 5
  }
  ],
  "weeks": 16,
  "shift_system": "4x4"
}


### test App.py
POST http://localhost:5000/solve
Content-Type: application/json

{
  "projects": [
    {
      "name": "Project A",
      "start": 0,
      "end": 3,
      "roles": {
        "developer": 2,
        "designer": 1
      }
    },
    {
      "name": "Project B",
      "start": 2,
      "end": 5,
      "roles": {
        "developer": 1
      }
    }
  ],
  "employees": [
    {
      "name": "Employee 1",
      "role": "developer",
      "expertise": 10,
      "availability": [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
    },
    {
      "name": "Employee 2",
      "role": "designer",
      "expertise": 8,
      "availability": [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
    }
  ],
  "weeks": 6,
  "shift_system": "3x3"
}

### test App.py second time
POST http://127.0.0.1:5000/solve
Content-Type: application/json

{
    "projects": [
        {
            "name": "Project A",
            "start": 0,
            "end": 4,
            "roles": {
                "developer": 2,
                "manager": 1
            }
        },
        {
            "name": "Project B",
            "start": 2,
            "end": 5,
            "roles": {
                "developer": 3
            }
        }
    ],
    "employees": [
        {
            "name": "John Doe",
            "role": "developer",
            "expertise": 5,
            "availability": [1, 1, 1, 0, 1, 1, 1]
        },
        {
            "name": "Jane Doe",
            "role": "manager",
            "expertise": 7,
            "availability": [1, 1, 1, 1, 0, 0, 0]
        }
    ],
    "weeks": 6,
    "shift_system": "3x3"
}
